model: "deepseek-ai/DeepSeek-V3.2"
run_baseline: false
baseline_args: ""
health_check:
  init_delay: 180
  timeout: 3000 # 50 minutes
  interval: 10.0

# Define benchmark cases
test_cases:
  
  sharegpt:
    type: sharegpt
    num_prompts: 1000
    dataset_path: "ShareGPT_V3_unfiltered_cleaned_split.json"

  random_32k:
    type: random
    input_len: 32000
    output_len: 100
    num_prompts: 100
    seed: 42

  random_4k:
    type: random
    input_len: 4000
    output_len: 200
    num_prompts: 500
    seed: 42

  random_2k:
    type: random
    input_len: 2000
    output_len: 100
    num_prompts: 500
    seed: 42

  random_128:
    type: random
    input_len: 128
    output_len: 4
    num_prompts: 1000
    seed: 42

  random_2k_output:
    type: random
    input_len: 1000
    output_len: 2000
    num_prompts: 100
    seed: 42
  
  random_128k:
    type: random
    input_len: 128000
    output_len: 100
    num_prompts: 100
    seed: 42

  random_2k_thinking:
    type: random
    input_len: 2000
    output_len: 100
    num_prompts: 500
    seed: 42
    args: '--extra_body={"chat_template_kwargs": {"thinking": True}}'

# Engine test configurations
runs:
  # - name: "sglang-official-recommended-tp-dp"
  #   engine: "sglang"
  #   conda_env: "sglang"
  #   args: "--tensor-parallel-size 8 --enable-dp-attention --chat-template ./tool_chat_template_deepseekv32.jinja --dp 8"
  #   test_cases:
  #     - random_32k
  #     - random_4k
  #     - random_2k
  #     - random_128
  #     - random_128k
  #     - random_2k_output

  - name: "vllm-tp"
    engine: "vllm"
    conda_env: "vllm"
    args: >
      --tensor-parallel-size 8
      --tokenizer-mode deepseek_v32
      --reasoning-parser deepseek_v3
    test_cases:
      - sharegpt
      - random_32k
      - random_4k
      - random_2k
      - random_128
      - random_128k
      - random_2k_output

  - name: "vllm-dp-ep-half-ctx"
    engine: "vllm"
    conda_env: "vllm"
    args: >
      --tensor-parallel-size 1
      --tokenizer-mode deepseek_v32
      --reasoning-parser deepseek_v3
      -dp 8
      --enable-expert-parallel
      --max-model-len 81920
    test_cases:
      - sharegpt

  - name: "vllm-tp-dcp"
    engine: "vllm"
    conda_env: "vllm"
    args: >
      --tokenizer-mode deepseek_v32
      --reasoning-parser deepseek_v3
      -tp 8
      -dcp 8
    test_cases:
      - sharegpt
  
  - name: "vllm-dp-ep-pplx"
    engine: "vllm"
    conda_env: "vllm"
    args: >
      --tensor-parallel-size 1
      --tokenizer-mode deepseek_v32
      --reasoning-parser deepseek_v3
      -dp 8
      --enable-expert-parallel
      --max-num-seqs 128
      --max-model-len 122880
      --all2all-backend pplx
    test_cases:
      - sharegpt
