model: "deepseek-ai/DeepSeek-V3.2"
run_baseline: false
baseline_args: ""
health_check:
  init_delay: 60
  timeout: 1800 # 30 minutes
  interval: 5.0

# Define benchmark cases
test_cases:
  
  sharegpt:
    type: sharegpt
    num_prompts: 1000
    dataset_path: "ShareGPT_V3_unfiltered_cleaned_split.json"

  random_32k:
    type: random
    input_len: 32000
    output_len: 100
    num_prompts: 100
    seed: 42

  random_4k:
    type: random
    input_len: 4000
    output_len: 200
    num_prompts: 500
    seed: 42

  random_2k:
    type: random
    input_len: 2000
    output_len: 100
    num_prompts: 500
    seed: 42

  random_128:
    type: random
    input_len: 128
    output_len: 4
    num_prompts: 1000
    seed: 42

  random_2k_output:
    type: random
    input_len: 1000
    output_len: 2000
    num_prompts: 100
    seed: 42

  random_2k_thinking:
    type: random
    input_len: 2000
    output_len: 100
    num_prompts: 500
    seed: 42
    args: '--extra_body={"chat_template_kwargs": {"thinking": True}}'

# Engine test configurations
runs:
  # - name: "sglang-official-recommended-tp-dp"
  #   engine: "sglang"
  #   conda_env: "sglang"
  #   envs:
  #     SGLANG_ENABLE_JIT_DEEPGEMM: "0"
  #   args: "--tensor-parallel-size 8 --enable-dp-attention --chat-template ./tool_chat_template_deepseekv32.jinja --dp 8"
  #   test_cases:
  #     - sharegpt

  # - name: "sglang-official-recommended-tp-dp-ep"
  #   engine: "sglang"
  #   conda_env: "sglang"
  #   envs:
  #     HF_HOME: /workspace/gpustack_cache
  #   args: "--tensor-parallel-size 8 --enable-dp-attention --chat-template ./tool_chat_template_deepseekv32.jinja --ep 8 --dp 8"
  #   test_cases:
  #     - sharegpt
  #     - random_32k
  #     - random_4k
  #     - random_2k
  #     - random_128
  #     - random_128k
  #     - random_2k_output

# Low
  # - name: "sglang-official-recommended-tp-dp-reasoning"
  #   engine: "sglang"
  #   conda_env: "sglang"
  #   envs:
  #     HF_HOME: /workspace/gpustack_cache
  #   args: >
  #     --tensor-parallel-size 8
  #     --enable-dp-attention 
  #     --chat-template ./tool_chat_template_deepseekv32.jinja 
  #     --dp 8 
  #     --reasoning-parser deepseek-v3
  #   test_cases:
  #     - sharegpt

  - name: "sglang-official-recommended-tp-dp-reasoning-tool-call"
    engine: "sglang"
    conda_env: "sglang"
    envs:
      HF_HOME: /workspace/gpustack_cache
    args: >
      --tensor-parallel-size 8 
      --enable-dp-attention 
      --chat-template ./tool_chat_template_deepseekv32.jinja 
      --dp 8 
      --reasoning-parser deepseek-v3 
      --tool-call-parser deepseekv32
    test_cases:
      - sharegpt

  - name: "sglang-official-tp-dp-cp"
    engine: "sglang"
    conda_env: "sglang"
    envs:
      HF_HOME: /workspace/gpustack_cache
    args: >
      --tensor-parallel-size 8
      --enable-dp-attention
      --chat-template ./tool_chat_template_deepseekv32.jinja
      --dp 8
      --enable-nsa-prefill-context-parallel
    test_cases:
      - sharegpt

  - name: "sglang-official-tp-dp-reason-tool-context-length-32k"
    engine: "sglang"
    conda_env: "sglang"
    envs:
      HF_HOME: /workspace/gpustack_cache
    args: >
      --tensor-parallel-size 8
      --enable-dp-attention
      --chat-template ./tool_chat_template_deepseekv32.jinja
      --dp 8
      --reasoning-parser deepseek-v3 
      --tool-call-parser deepseekv32
      --context-length=32768
    test_cases:
      - sharegpt

  - name: "sglang-official-tp-dp-context-length-32k-kv-cache-type" # default is fpfloat16
    engine: "sglang"
    conda_env: "sglang"
    envs:
      HF_HOME: /workspace/gpustack_cache
    args: >
      --tensor-parallel-size 8
      --enable-dp-attention
      --chat-template ./tool_chat_template_deepseekv32.jinja
      --dp 8
      --reasoning-parser deepseek-v3 
      --tool-call-parser deepseekv32
      --context-length=32768
      --kv-cache-dtype fp8_e4m3
    test_cases:
      - sharegpt

  - name: "sglang-official-tp-dp-context-length-32k-kv-cache-type-fp8" # default is fpfloat16
    engine: "sglang"
    conda_env: "sglang"
    envs:
      HF_HOME: /workspace/gpustack_cache
    args: >
      --tensor-parallel-size 8
      --enable-dp-attention
      --chat-template ./tool_chat_template_deepseekv32.jinja
      --dp 8
      --reasoning-parser deepseek-v3 
      --tool-call-parser deepseekv32
      --context-length=32768
      --kv-cache-dtype fp8
    test_cases:
      - sharegpt

# Attention, different backends
  - name: "sglang-official-tp-dp-context-length-32k-backend-flashmla-sparse-kv"
    engine: "sglang"
    conda_env: "sglang"
    envs:
      HF_HOME: /workspace/gpustack_cache
    args: >
      --tensor-parallel-size 8
      --enable-dp-attention
      --chat-template ./tool_chat_template_deepseekv32.jinja
      --dp 8
      --reasoning-parser deepseek-v3 
      --tool-call-parser deepseekv32
      --context-length=32768
      --attention-backend nsa
      --nsa-prefill-backend flashmla_sparse
      --nsa-decode-backend flashmla_kv
    test_cases:
      - sharegpt

  - name: "sglang-official-tp-dp-context-length-32k-backend-fa3-fa3"
    engine: "sglang"
    conda_env: "sglang"
    envs:
      HF_HOME: /workspace/gpustack_cache
    args: >
      --tensor-parallel-size 8
      --enable-dp-attention
      --chat-template ./tool_chat_template_deepseekv32.jinja
      --dp 8
      --reasoning-parser deepseek-v3 
      --tool-call-parser deepseekv32
      --context-length=32768
      --attention-backend nsa
      --nsa-prefill-backend fa3
      --nsa-decode-backend fa3
    test_cases:
      # - sharegpt
      - random_32k
      - random_4k
      - random_2k
      - random_128
      - random_128k
      - random_2k_output

# Torch Compile
# torch.compile accelerates small models on small batch sizes
# Skip
  # - name: "sglang-torch-compile"
  #   engine: "sglang"
  #   conda_env: "sglang"
  #   envs:
  #   args: "-tp 8 --enable-torch-compile"
  #   test_cases:
  #     - sharegpt

# EP
# Skip
  # - name: "sglang-ep" # resource not enough on 8-GPU machine, need 64-GPUs
  #   engine: "sglang"
  #   conda_env: "sglang"
  #   args: "-tp 8 --cuda-graph-max-bs 256 --ep-size 8"
  #   test_cases:
  #     - sharegpt

# CUDA Graph, related to batch size and QPS, not tested this time
# Skip
  # - name: "sglang-cuda-graph" # qps 10-50
  #   engine: "sglang"
  #   conda_env: "sglang"
  #   args: "-tp 8 --cuda-graph-max-bs 128"
  #   test_cases:
  #     - sharegpt
  
  # - name: "sglang-cuda-graph" # qps>50
  #   engine: "sglang"
  #   conda_env: "sglang"
  #   args: "-tp 8 --cuda-graph-max-bs 256"
  #   test_cases:
  #     - sharegpt

# Attention, H200: `flashmla_sparse` prefill attention (short-seq prefill uses MHA via FlashAttention varlen), `fa3` decode attention, `bf16` kv cache dtype
