model: "deepseek-ai/DeepSeek-V3.2"
run_baseline: false
baseline_args: ""
health_check:
  init_delay: 180
  timeout: 1800 # 30 minutes
  interval: 5.0

# Define benchmark cases
test_cases:
  
  sharegpt:
    type: sharegpt
    num_prompts: 1000
    dataset_path: "ShareGPT_V3_unfiltered_cleaned_split.json"

  random_32k:
    type: random
    input_len: 32000
    output_len: 100
    num_prompts: 100
    seed: 42

  random_4k:
    type: random
    input_len: 4000
    output_len: 200
    num_prompts: 500
    seed: 42

  random_2k:
    type: random
    input_len: 2000
    output_len: 100
    num_prompts: 500
    seed: 42

  random_128:
    type: random
    input_len: 128
    output_len: 4
    num_prompts: 1000
    seed: 42

  random_2k_output:
    type: random
    input_len: 1000
    output_len: 2000
    num_prompts: 100
    seed: 42

  random_2k_thinking:
    type: random
    input_len: 2000
    output_len: 100
    num_prompts: 500
    seed: 42
    args: '--extra_body={"chat_template_kwargs": {"thinking": True}}'

# Engine test configurations
runs:
  - name: "sglang-no-chat-template"
    engine: "sglang"
    conda_env: "sglang"
    args: "--tensor-parallel-size 8"
    test_cases:
      - sharegpt
  # after test: 根据结果调整下面的参数

# Low
  # - name: "sglang-loader-extra-config"
  #   engine: "sglang"
  #   conda_env: "sglang"
  #   args: >
  #     --tensor-parallel-size 8
  #     --model-loader-extra-config {"enable_multithread_load": true}
  #   test_cases:
  #     - sharegpt

  - name: "sglang-dp-attention"
    engine: "sglang"
    conda_env: "sglang"
    args: "--tensor-parallel-size 8 --chat-template ./tool_chat_template_deepseekv32.jinja --enable-dp-attention"
    test_cases:
      - sharegpt

  - name: "sglang-official-recommended-tp-dp"
    engine: "sglang"
    conda_env: "sglang"
    args: "--tensor-parallel-size 8 --enable-dp-attention --chat-template ./tool_chat_template_deepseekv32.jinja --dp 8"
    test_cases:
      - sharegpt
  # after test: 可能根据结果排除所有包含dp的测试

  - name: "sglang-official-recommended-tp-dp-ep"
    engine: "sglang"
    conda_env: "sglang"
    args: "--tensor-parallel-size 8 --enable-dp-attention --chat-template ./tool_chat_template_deepseekv32.jinja --ep 8 --dp 8"
    test_cases:
      - sharegpt

  - name: "sglang-official-mpt-tp-dp-cp" # 考虑：添加 --cuda-graph-max-bs 32, 是否要加speculative decoding，根据上一个测试的结果来看
    engine: "sglang"
    conda_env: "sglang"
    args: >
      --tensor-parallel-size 8
      --enable-dp-attention
      --chat-template ./tool_chat_template_deepseekv32.jinja
      --dp 8
      --enable-nsa-prefill-context-parallel
    test_cases:
      - sharegpt

  - name: "sglang-official-mpt-tp-dp-ep-cp" # 考虑：添加 --cuda-graph-max-bs 32, 是否要加speculative decoding，根据上一个测试的结果来看
    engine: "sglang"
    conda_env: "sglang"
    args: >
      --tensor-parallel-size 8
      --enable-dp-attention
      --chat-template ./tool_chat_template_deepseekv32.jinja
      --dp 8
      --enable-nsa-prefill-context-parallel
      --ep 8
    test_cases:
      - sharegpt

  # before test: 检查是否要去掉dp
  - name: "sglang-speculative-decoding-mtp-step3-env-max-req-256"
    engine: "sglang"
    conda_env: "sglang"
    args: >
      --tensor-parallel-size 8
      --chat-template ./tool_chat_template_deepseekv32.jinja
      --dp 8
      --enable-dp-attention
      --speculative-algorithm EAGLE
      --speculative-num-steps 3
      --speculative-eagle-topk 1
      --speculative-num-draft-tokens 4
      --max-running-requests 256
    test_cases:
      - sharegpt

# Low
  # - name: "sglang-speculative-decoding-mtp-step3-env-max-req-128" # TODO: double check mem-frac
  #   engine: "sglang"
  #   conda_env: "sglang"
  #   args: >
  #     --tensor-parallel-size 8
  #     --dp 8
  #     --chat-template ./tool_chat_template_deepseekv32.jinja
  #     --enable-dp-attention
  #     --speculative-algorithm EAGLE
  #     --speculative-num-steps 3
  #     --speculative-eagle-topk 1
  #     --speculative-num-draft-tokens 4
  #     --max-running-requests 128
  #   test_cases:
  #     - sharegpt

  # - name: "sglang-official-mpt-tp-cp" # 考虑：添加 --cuda-graph-max-bs 32
  #   engine: "sglang"
  #   conda_env: "sglang"
  #   args: >
  #     --chat-template ./tool_chat_template_deepseekv32.jinja
  #     --trust-remote-code
  #     --tp 8
  #     --enable-dp-attention
  #     --speculative-algorithm EAGLE
  #     --speculative-num-steps 3
  #     --speculative-eagle-topk 1
  #     --speculative-num-draft-tokens 4
  #     --mem-frac 0.7
  #     --max-running-requests 256
  #     --enable-nsa-prefill-context-parallel
  #   test_cases:
  #     - sharegpt

  # - name: "sglang-official-mtp-tp-ep"
  #   engine: "sglang"
  #   conda_env: "sglang"
  #   args: >
  #     --chat-template ./tool_chat_template_deepseekv32.jinja
  #     --trust-remote-code
  #     --tp 8
  #     --ep 8
  #     --enable-dp-attention
  #     --speculative-algorithm EAGLE
  #     --speculative-num-steps 3
  #     --speculative-eagle-topk 1
  #     --speculative-num-draft-tokens 4
  #     --mem-frac 0.7
  #     --max-running-requests 256
  #   test_cases:
  #     - sharegpt

  # - name: "sglang-official-mtp-tp-ep-cp"
  #   engine: "sglang"
  #   conda_env: "sglang"
  #   args: >
  #     --chat-template ./tool_chat_template_deepseekv32.jinja
  #     --trust-remote-code
  #     --tp 8
  #     --ep 8
  #     --enable-dp-attention
  #     --speculative-algorithm EAGLE
  #     --speculative-num-steps 3
  #     --speculative-eagle-topk 1
  #     --speculative-num-draft-tokens 4
  #     --mem-frac 0.7
  #     --max-running-requests 256
  #     --enable-nsa-prefill-context-parallel
  #   test_cases:
  #     - sharegpt

  - name: "vllm-dp-ep"
    engine: "vllm"
    conda_env: "vllm"
    args: >
      --tensor-parallel-size 1
      --tokenizer-mode deepseek_v32
      --reasoning-parser deepseek_v3
      -dp 8
      --enable-expert-parallel
    test_cases:
      - sharegpt
      - random_32k
      - random_4k
      - random_2k
      - random_128
      - random_2k_output
  
  - name: "vllm-dp-ep-pplx"
    engine: "vllm"
    conda_env: "vllm"
    args: >
      --tensor-parallel-size 1
      --tokenizer-mode deepseek_v32
      --reasoning-parser deepseek_v3
      -dp 8
      --enable-expert-parallel
      --all2all-backend pplx
    test_cases:
      - sharegpt

  - name: "vllm-tp-dcp"
    engine: "vllm"
    conda_env: "vllm"
    args: >
      --tokenizer-mode deepseek_v32
      --reasoning-parser deepseek_v3
      -tp 8
      -dcp 8
    test_cases:
      - sharegpt
  - name: "vllm-tp-short-ctx-bf16"
    engine: "vllm"
    conda_env: "vllm"
    args: >
      --tokenizer-mode deepseek_v32
      --reasoning-parser deepseek_v3
      -tp 8
      -dcp 8
      --kv-cache-dtype bfloat16
    test_cases:
      - random_128